/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Copier.java
 *
 * Created on 11 Σεπ 2010, 8:23:38 μμ
 */
package jphotos.tools;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import jphotos.Photos;

/**
 *
 * @author lordovol
 */
public class Copier extends MyDraggable {

  private ArrayList<File> files;
  private final File dest;

  /** Creates new form Copier */
  public Copier() {
    this(null,null);
  }

 public Copier(ArrayList<File> files, File dest) {
    this.files = files;
    this.dest = dest;
    initComponents();
    setLocationRelativeTo(null);

    Copy c = new Copy();
    Thread t = new Thread(c);
    t.start();
    setVisible(true);

  }

  private void process() {
    Copy c = new Copy();
    Thread t = new Thread(c);
    t.start();
  }

  class Copy implements Runnable {

    long total = 0;
    long cur = 0;

    public Copy() {
      for (Iterator<File> it = files.iterator(); it.hasNext();) {
        File file = it.next();
        total += file.length();
      }
    }

    public void run() {
      File destinationPath = new File(dest + "/photos_" + Tools.getNow().replaceAll("/", "_")+"_"+ Photos.curListId);
      l_dest.setText("Αντιγραφή στο φάκελο :" + destinationPath.getAbsolutePath());
      boolean mkdir = destinationPath.mkdir();
      if(!mkdir){
         Tools.error("Αποθήκευση φωτογραφιών", "Κάποιο σφάλμα συνέβει");
        return;
      }
      for (Iterator<File> it = files.iterator(); it.hasNext();) {
        File file = it.next();
        cur += file.length();
        l_name.setText("Αντιγραφή: "+file.getName());
        try {
          String newFile = Tools.createPhotoName(destinationPath,file);
          Tools.copyfile(file.getAbsolutePath(), newFile);
        } catch (FileNotFoundException ex) {
          Photos.logger.log(Level.SEVERE, null, ex);
          Tools.error("Αποθήκευση φωτογραφιών", "Κάποιο σφάλμα συνέβει");
        } catch (IOException ex) {
          Photos.logger.log(Level.SEVERE, null, ex);
          Tools.error("Αποθήκευση φωτογραφιών", "Κάποιο σφάλμα συνέβει");
        }
        progress.setValue((int) (cur * 100 / total));
      }
      progress.setValue(0);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    l_name = new javax.swing.JLabel();
    progress = new javax.swing.JProgressBar();
    bt_close = new javax.swing.JButton();
    l_dest = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

    jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+3));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("Αντιγραφή φωτογραφιών");

    progress.setStringPainted(true);

    bt_close.setText("Κλείσιμο");
    bt_close.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        bt_closeActionPerformed(evt);
      }
    });

    l_dest.setText(" ");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(bt_close))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(l_name, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(66, 66, 66)
            .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(l_dest, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(l_dest)
        .addGap(24, 24, 24)
        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
        .addComponent(bt_close)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeActionPerformed
      dispose();
    }//GEN-LAST:event_bt_closeActionPerformed
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton bt_close;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JLabel l_dest;
  private javax.swing.JLabel l_name;
  private javax.swing.JProgressBar progress;
  // End of variables declaration//GEN-END:variables
}
