/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GridPanel.java
 *
 * Created on 2 Σεπ 2010, 6:13:48 μμ
 */
package jphotos.panes;

import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import jphotos.database.FileRecord;

/**
 *
 * @author lordovol
 */
public class GridPanel extends javax.swing.JPanel {

  public static final long serialVersionUID = 23534634654764L;
  public ScrollableFlowPanel photoPanel;
 

  /** Creates new form GridPanel */
  public GridPanel() {
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 336, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 464, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  public void setPhotos(ArrayList<FileRecord> datePhotos) {
    removeAll();
    photoPanel = new ScrollableFlowPanel();
    JScrollPane panel = new JScrollPane(photoPanel);
    panel.getViewport().setOpaque(false);
    panel.setOpaque(false);
    photoPanel.setOpaque(false);
    panel.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    add(panel);
    //photoPanel.setLayout(new GridLayout((datePhotos.size()/4) + 1,4));
    photoPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
    int count = 0;
    for (Iterator<FileRecord> it = datePhotos.iterator(); it.hasNext();) {
      FileRecord fileRecord = it.next();
      PhotoPanel p = new PhotoPanel(fileRecord,count);
      photoPanel.add(p);
      count++;
    }
    revalidate();
    repaint();
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
