/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InfoPanel.java
 *
 * Created on 2 Σεπ 2010, 6:12:03 μμ
 */
package jphotos.panes;

import java.awt.FlowLayout;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import jphotos.database.FileRecord;
import jphotos.database.Print;

/**
 *
 * @author lordovol
 */
public class PrintsPanel extends javax.swing.JPanel {
  private final ScrollableFlowPanel photoPanel;
  private final JScrollPane panel;
  private FileRecord fileRecord;
  private Print print;

  /** Creates new form InfoPanel */
  public PrintsPanel() {
    initComponents();
    photoPanel = new ScrollableFlowPanel();
    photoPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
    panel = new JScrollPane(photoPanel);
    panel.setBorder(null);
    panel.getViewport().setOpaque(false);
    panel.setOpaque(false);
    photoPanel.setOpaque(false);
    panel.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
    add(panel);
    //photoPanel.setLayout(new GridLayout((datePhotos.size()/4) + 1,4));
    
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 470, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 228, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  void addPhoto(FileRecord fileRecord, Print print) {
    this.fileRecord = fileRecord;
    this.print = print;
    PhotoPanelThumb p = new PhotoPanelThumb(photoPanel, fileRecord, print);
    photoPanel.add(p);
    revalidate();
    repaint();
  }

  public void clearPrints() {
    photoPanel.removeAll();
    revalidate();
    repaint();
  }


  // Variables declaration - do not modify//GEN-BEGIN:variables
  // End of variables declaration//GEN-END:variables
}
